Modules/NGM.VoteUpDown/Models/Constants.cs
namespace NGM.VoteUpDown.Models {
    public static class Constants {
        public const string Dimension = "VoteUpDown";
    }
}

Modules/NGM.VoteUpDown/Models/VoteUpDownPart.cs
using Orchard.ContentManagement;

namespace NGM.VoteUpDown.Models {
    public class VoteUpDownPart : ContentPart {
        public bool ShowVoter { get; set; }

        public bool AllowAnonymousRatings { get; set; }

        public double ResultValue { get; set; }

        public double UserRating { get; set; }
    }
}

Modules/NGM.VoteUpDown/Controllers/VoteController.cs
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using Contrib.Voting.Services;
using NGM.VoteUpDown.Handlers;
using NGM.VoteUpDown.Models;
using Orchard;
using Orchard.ContentManagement;
using Orchard.Localization;
using Orchard.Mvc.Extensions;

namespace NGM.VoteUpDown.Controllers {
    public class VoteController  : Controller {
        private readonly IOrchardServices _orchardServices;
        private readonly IContentManager _contentManager;
        private readonly IVotingService _votingService;

        public VoteController(IOrchardServices orchardServices, IContentManager contentManager, IVotingService votingService) {
            _orchardServices = orchardServices;
            _contentManager = contentManager;
            _votingService = votingService;
            T = NullLocalizer.Instance;
        }

        public Localizer T { get; set; }

        [HttpPost, ActionName("Apply")]
        [FormValueRequired("submit.UpVote")]
        public ActionResult Apply_UpVote(int contentId, string returnUrl) { 
            return Apply(contentId, true, returnUrl); 
        }

        [HttpPost, ActionName("Apply")]
        [FormValueRequired("submit.DownVote")]
        public ActionResult Apply_DownVote(int contentId, string returnUrl) {
            return Apply(contentId, false, returnUrl);
        }

        private ActionResult Apply(int contentId, bool voteUp, string returnUrl) {
            var content = _contentManager.Get(contentId);
            if (content == null || !content.Has<VoteUpDownPart>() || !content.As<VoteUpDownPart>().ShowVoter)
                return this.RedirectLocal(returnUrl, "~/");

            var currentUser = _orchardServices.WorkContext.CurrentUser;
            if ((currentUser == null && !content.As<VoteUpDownPart>().AllowAnonymousRatings))
                return this.RedirectLocal(returnUrl, "~/");

            int rating = voteUp ? 1 : -1;

            if (currentUser != null) {
                var currentVote = _votingService.Get(vote => vote.Username == currentUser.UserName && vote.ContentItemRecord == content.Record && vote.Dimension == Constants.Dimension).FirstOrDefault();

                if (currentVote != null && (currentVote.Value + rating == 0)) {
                    _votingService.RemoveVote(currentVote);
                }
                else {
                    if (currentVote != null)
                        _votingService.ChangeVote(currentVote, rating);
                    else
                        _votingService.Vote(content, currentUser.UserName, HttpContext.Request.UserHostAddress, rating, Constants.Dimension);
                }
            }
            else {
                var anonHostname = HttpContext.Request.UserHostAddress;
                if (!string.IsNullOrWhiteSpace(HttpContext.Request.Headers["X-Forwarded-For"]))
                    anonHostname += "-" + HttpContext.Request.Headers["X-Forwarded-For"];

                var currentVote = _votingService.Get(vote => vote.Username == "Anonymous" && vote.Hostname == anonHostname && vote.ContentItemRecord == content.Record && vote.Dimension == Constants.Dimension).FirstOrDefault();
                if (rating > 0 && currentVote == null)
                    _votingService.Vote(content, "Anonymous", anonHostname, rating, Constants.Dimension);
            }

            return this.RedirectLocal(returnUrl, "~/");
        }
    }

    public class FormValueRequiredAttribute : ActionMethodSelectorAttribute {
        private readonly string _submitButtonName;

        public FormValueRequiredAttribute(string submitButtonName) {
            _submitButtonName = submitButtonName;
        }

        public override bool IsValidForRequest(ControllerContext controllerContext, MethodInfo methodInfo) {
            var value = controllerContext.HttpContext.Request.Form[_submitButtonName];
            return !string.IsNullOrEmpty(value);
        }
    }
}

Modules/NGM.VoteUpDown/Views/DefinitionTemplates/VoteUpDownTypePartSettings.cshtml
@model NGM.VoteUpDown.Settings.VoteUpDownTypePartSettings
<fieldset>
    <div>
        @Html.EditorFor(m => m.ShowVoter)
        <label class="forcheckbox" for="@Html.FieldIdFor(m => m.ShowVoter)">@T("Enable up/down rating")</label>
    </div>
    <div>
        @Html.EditorFor(m => m.AllowAnonymousRatings)
        <label class="forcheckbox" for="@Html.FieldIdFor(m => m.AllowAnonymousRatings)">@T("Allow anonymous ratings")</label>
    </div>
</fieldset>

Modules/NGM.VoteUpDown/Views/Parts.VoteUpDown.Summary.cshtml
@using Orchard.Utility.Extensions;
@{
    Style.Require("NGM.VoteUpDown");
}
<div class="vote-count">@T.Plural("1 vote", "{0} votes", (int)Model.ResultValue)</div>

Modules/NGM.VoteUpDown/Views/Parts.VoteUpDown.SummaryAdmin.cshtml
@using Orchard.Utility.Extensions;
@{
    Style.Require("NGM.VoteUpDown");
}
<div class="updown-rating-admin">
  <h3>@T("Rating:")</h3>
  <span class="rating">@Model.UserRating</span>
</div>

Modules/NGM.VoteUpDown/Views/Parts.VoteUpDown.UserSummary.cshtml
@using Orchard.Utility.Extensions;
@{
    Style.Require("NGM.VoteUpDown");
}
<div class="user-vote-count">@T.Plural("1 vote", "{0} votes", (int)Model.UserRating)</div>

Modules/NGM.VoteUpDown/Views/Parts.VoteUpDown.cshtml
@using Orchard.Utility.Extensions;
@{
    Style.Require("NGM.VoteUpDown");

    double roundedResult = Math.Round(Model.ResultValue * 2, MidpointRounding.AwayFromZero) / 2;
    string currentResultClass = string.Format("updown-value-{0}", Math.Floor(roundedResult));

    double userRating = Model.UserRating;
    bool userCanRate = Request.IsAuthenticated || Model.AllowAnonymousRatings;
    if (userCanRate && !Request.IsAuthenticated && Request.Cookies["Orchrd__updown"] != null && !string.IsNullOrWhiteSpace(Request.Cookies["Orchrd__updown"].Value)) {
      userRating = Convert.ToDouble(Request.Cookies["Orchrd__updown"].Value);
    }
    string canRateClass = userCanRate ? "updown-can-rate" : "";
    string userRatingClass = userCanRate && userRating > 0 ? string.Format("updown-user-rating-{0}", userRating) : "";
}
<div class="updown-rating @canRateClass">
  @using (Html.BeginFormAntiForgeryPost(Url.Action("Apply", "Vote", new { area = "NGM.VoteUpDown" }), FormMethod.Post, new {@class = "rate"})) {  
      <button class="voteupdown up-submit" name="submit.UpVote" type="submit" value="true">@T("Vote Up")</button>
      <div class="updown-current-result @currentResultClass @userRatingClass">
        <span class="vote-count">@Model.ResultValue</span>
      </div>
      <button class="voteupdown down-submit" name="submit.DownVote" type="submit" value="false">@T("Vote Down")</button>
      @Html.Hidden("contentId", (int)Model.ContentItem.Id)
      @Html.Hidden("ReturnUrl", Context.Request.ToUrlString()) 
  }
</div>